<a href="https://colab.research.google.com/github/Prathambiradr12345/Machine-_learning/blob/main/Question_No_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

# Load the Titanic dataset
titanic_data = pd.read_csv('tested.csv')

# Create a time series index
titanic_data['Boarding Time'] = pd.date_range(start='1912-04-10', periods=len(titanic_data), freq='min')
titanic_data.set_index('Boarding Time', inplace=True)

# Resample the data to 10-minute intervals, calculating the mean only for numeric columns
resampled_data = titanic_data.resample('10min').agg(
    {col: 'mean' for col in titanic_data.select_dtypes(include=['number']).columns}
)
# Explanation:
# 1. We use .agg() for more control over aggregation.
# 2. We create a dictionary to specify 'mean' for numeric columns only.
# 3. titanic_data.select_dtypes(include=['number']).columns selects only the numeric columns.

# Print the resampled data
resampled_data.head()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
Boarding Time,,,,,,,
1912-04-10 00:00:00,896.5,0.4,2.8,30.150000,0.5,0.2,12.27001
1912-04-10 00:10:00,906.5,0.5,2.1,36.777778,0.5,0.0,26.57833
1912-04-10 00:20:00,916.5,0.3,1.8,33.562500,0.5,0.6,55.38917
1912-04-10 00:30:00,926.5,0.4,2.6,28.785714,0.6,0.4,24.92125
1912-04-10 00:40:00,936.5,0.4,2.1,40.125000,0.1,0.3,25.09376

# **Rolling Statitics**

In [4]:
import pandas as pd

# Load the Titanic dataset
titanic_data = pd.read_csv('tested.csv')

# Create a time series index
titanic_data['Boarding Time'] = pd.date_range(start='1912-04-10', periods=len(titanic_data), freq='min')
titanic_data.set_index('Boarding Time', inplace=True)

# Calculate rolling mean and standard deviation
rolling_mean = titanic_data['Age'].rolling(window=10).mean()
rolling_std = titanic_data['Age'].rolling(window=10).std()

# Print the rolling statistics
print(rolling_mean.head())
print(rolling_std.head())

Boarding Time
1912-04-10 00:00:00   NaN
1912-04-10 00:01:00   NaN
1912-04-10 00:02:00   NaN
1912-04-10 00:03:00   NaN
1912-04-10 00:04:00   NaN
Name: Age, dtype: float64
Boarding Time
1912-04-10 00:00:00   NaN
1912-04-10 00:01:00   NaN
1912-04-10 00:02:00   NaN
1912-04-10 00:03:00   NaN
1912-04-10 00:04:00   NaN
Name: Age, dtype: float64

# **Laging**

In [7]:
import pandas as pd

# Load the Titanic dataset
titanic_data = pd.read_csv('tested.csv')

# Create a time series index
titanic_data['Boarding Time'] = pd.date_range(start='1912-04-10', periods=len(titanic_data), freq='min')
titanic_data.set_index('Boarding Time', inplace=True)

# Calculate lagged values
lagged_age = titanic_data['Age'].shift(1)
lagged_survived = titanic_data['Survived'].shift(1)

# Print the lagged values
print(lagged_age.head())
print(lagged_survived.head())

Boarding Time
1912-04-10 00:00:00     NaN
1912-04-10 00:01:00    34.5
1912-04-10 00:02:00    47.0
1912-04-10 00:03:00    62.0
1912-04-10 00:04:00    27.0
Name: Age, dtype: float64
Boarding Time
1912-04-10 00:00:00    NaN
1912-04-10 00:01:00    0.0
1912-04-10 00:02:00    1.0
1912-04-10 00:03:00    0.0
1912-04-10 00:04:00    0.0
Name: Survived, dtype: float64

# **Exponetial Smoothing**

In [9]:
import pandas as pd

# Load the Titanic dataset
titanic_data = pd.read_csv('tested.csv')

# Create a time series index
titanic_data['Boarding Time'] = pd.date_range(start='1912-04-10', periods=len(titanic_data), freq='min')
titanic_data.set_index('Boarding Time', inplace=True)

# Calculate exponential smoothing
from statsmodels.tsa.holtwinters import SimpleExpSmoothing
ses_model = SimpleExpSmoothing(titanic_data['Age'])
ses_model_fit = ses_model.fit()

# Print the smoothed values
print(ses_model_fit.fittedvalues.head())

Boarding Time
1912-04-10 00:00:00    34.500000
1912-04-10 00:01:00    34.500000
1912-04-10 00:02:00    34.562500
1912-04-10 00:03:00    34.699688
1912-04-10 00:04:00    34.661189
dtype: float64

/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency min will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/holtwinters/model.py:918: ConvergenceWarning: Optimization failed to converge. Check mle_retvals.
  warnings.warn(

In [14]:
import pandas as pd
import statsmodels.api as sm

# Load the Titanic dataset
titanic_data = pd.read_csv('tested.csv')

# Create a time series index
titanic_data['Boarding Time'] = pd.date_range(start='1912-04-10', periods=len(titanic_data), freq='min')
titanic_data.set_index('Boarding Time', inplace=True)

# Handle missing values in 'Age' column before decomposition
titanic_data['Age'].fillna(titanic_data['Age'].mean(), inplace=True)

# Decompose the time series after handling missing values
# Adjust the period to match the data's actual seasonality (or frequency)
# For example, if you expect hourly seasonality, use period=60 (60 minutes)
# or you could determine your frequency by autocorrelation and partialautocorrelation
# functions
decomposition = sm.tsa.seasonal_decompose(titanic_data['Age'], model='additive', period=60)

# Print the decomposed components
print(decomposition.trend.head())
print(decomposition.seasonal.head())
print(decomposition.resid.head())

Boarding Time
1912-04-10 00:00:00   NaN
1912-04-10 00:01:00   NaN
1912-04-10 00:02:00   NaN
1912-04-10 00:03:00   NaN
1912-04-10 00:04:00   NaN
Name: trend, dtype: float64
Boarding Time
1912-04-10 00:00:00   -3.284864
1912-04-10 00:01:00    3.056000
1912-04-10 00:02:00    1.622081
1912-04-10 00:03:00   -3.115844
1912-04-10 00:04:00   -4.092256
Name: seasonal, dtype: float64
Boarding Time
1912-04-10 00:00:00   NaN
1912-04-10 00:01:00   NaN
1912-04-10 00:02:00   NaN
1912-04-10 00:03:00   NaN
1912-04-10 00:04:00   NaN
Name: resid, dtype: float64

<ipython-input-14-d8a5f595d294>:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  titanic_data['Age'].fillna(titanic_data['Age'].mean(), inplace=True)

In [17]:
import pandas as pd
import statsmodels.api as sm

# Load the Titanic dataset
titanic_data = pd.read_csv('tested.csv')

# Create a time series index
titanic_data['Boarding Time'] = pd.date_range(start='1912-04-10', periods=len(titanic_data), freq='min')
titanic_data.set_index('Boarding Time', inplace=True)

# Fit an ARIMA model
from statsmodels.tsa.arima.model import ARIMA
arima_model = ARIMA(titanic_data['Age'], order=(1,1,1))
arima_model_fit = arima_model.fit()

# Print the ARIMA model summary
df=arima_model_fit.summary()
df

/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency min will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency min will be used.
  self._init_dates(dates, freq)
/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency min will be used.
  self._init_dates(dates, freq)

<class 'statsmodels.iolib.summary.Summary'>
"""
                               SARIMAX Results
==============================================================================
Dep. Variable:                    Age   No. Observations:                  418
Model:                 ARIMA(1, 1, 1)   Log Likelihood               -1349.329
Date:                Thu, 24 Oct 2024   AIC                           2704.658
Time:                        11:36:57   BIC                           2716.757
Sample:                    04-10-1912   HQIC                          2709.441
                         - 04-10-1912
Covariance Type:                  opg
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
ar.L1         -0.0892      0.063     -1.408      0.159      -0.213       0.035
ma.L1         -0.9995      0.126     -7.953      0.000      -1.246      -0.753
sigma2       199.5323     30.411      6.561      0.000     139.927     259.137
===================================================================================
Ljung-Box (L1) (Q):                   0.02   Jarque-Bera (JB):                22.24
Prob(Q):                              0.89   Prob(JB):                         0.00
Heteroskedasticity (H):               1.03   Skew:                             0.44
Prob(H) (two-sided):                  0.85   Kurtosis:                         3.70
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).
"""