<a href="https://colab.research.google.com/github/Prathambiradr12345/Machine-_learning/blob/main/Working_with_date%26_time-2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
date=pd.read_csv('orders.csv')
time=pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

working with dates

#converting to datetime datatype

In [11]:
date['date']=pd.to_datetime(date['date'])

In [7]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

Extract year

In [12]:
date['date_year']=date['date'].dt.year

In [8]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [13]:
date['date_month']=date['date'].dt.month
date.head()

        date  product_id  city_id  orders  date_year  date_month
0 2019-12-10        5628       25       3       2019          12
1 2018-08-15        3646       14     157       2018           8
2 2018-10-23        1859       25       1       2018          10
3 2019-08-17        7292       25       1       2019           8
4 2019-01-06        4344       25       3       2019           1

In [14]:
date['date_day']=date['date'].dt.day
date.head()

        date  product_id  city_id  orders  date_year  date_month  date_day
0 2019-12-10        5628       25       3       2019          12        10
1 2018-08-15        3646       14     157       2018           8        15
2 2018-10-23        1859       25       1       2018          10        23
3 2019-08-17        7292       25       1       2019           8        17
4 2019-01-06        4344       25       3       2019           1         6

week of days

In [15]:
date['week_of_day']=date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_day,week_of_day
0,2019-12-10,5628,25,3,2019,12,10,1
1,2018-08-15,3646,14,157,2018,8,15,2
2,2018-10-23,1859,25,1,2018,10,23,1
3,2019-08-17,7292,25,1,2019,8,17,5
4,2019-01-06,4344,25,3,2019,1,6,6

Extract time elasped between dates

is weekend

In [16]:
import datetime
today=datetime.datetime.today()
today

datetime.datetime(2024, 9, 6, 12, 9, 17, 850271)

In [17]:
today-date['date']

0     1732 days 12:09:17.850271
1     2214 days 12:09:17.850271
2     2145 days 12:09:17.850271
3     1847 days 12:09:17.850271
4     2070 days 12:09:17.850271
                 ...
995   2160 days 12:09:17.850271
996   2101 days 12:09:17.850271
997   1949 days 12:09:17.850271
998   2014 days 12:09:17.850271
999   1788 days 12:09:17.850271
Name: date, Length: 1000, dtype: timedelta64[ns]

In [18]:
(today-date['date']).dt.days

0      1732
1      2214
2      2145
3      1847
4      2070
       ...
995    2160
996    2101
997    1949
998    2014
999    1788
Name: date, Length: 1000, dtype: int64

In [22]:
#month
np.round((today-date['date']) /np.timedelta64(1, 'M'),0)

ValueError: Unit M is not supported. Only unambiguous timedelta values durations are supported. Allowed units are 'W', 'D', 'h', 'm', 's', 'ms', 'us', 'ns'

In [23]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [24]:
time['date']=pd.to_datetime(time['date'])

In [25]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [26]:
time['date']=pd.to_datetime(time['date'])

In [27]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [28]:
time['hour']=time['date'].dt.hour
time['min']=time['date'].dt.minute
time['sec']=time['date'].dt.second
time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [29]:
#extract time part
time['time']=time['date'].dt.time
time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [30]:
#time difference
today-time['date']

0     3918 days 11:19:17.850271
1     3782 days 12:29:17.850271
2     4268 days 11:48:17.850271
3     3570 days 11:38:17.850271
4     3967 days 12:58:17.850271
                 ...
995   4557 days 11:19:17.850271
996   3878 days 12:55:17.850271
997   4343 days 12:32:17.850271
998   4459 days 12:35:17.850271
999   3731 days 12:44:17.850271
Name: date, Length: 1000, dtype: timedelta64[ns]

In [31]:
#in seconds
(today-time['date'])/np.timedelta64(1,'s')

0      3.385560e+08
1      3.268098e+08
2      3.687977e+08
3      3.084899e+08
4      3.427955e+08
           ...
995    3.937656e+08
996    3.351057e+08
997    3.752803e+08
998    3.853029e+08
999    3.224043e+08
Name: date, Length: 1000, dtype: float64

In [32]:
(today-time['date'])/np.timedelta64(1,'m')

0      5.642599e+06
1      5.446829e+06
2      6.146628e+06
3      5.141498e+06
4      5.713258e+06
           ...
995    6.562759e+06
996    5.585095e+06
997    6.254672e+06
998    6.421715e+06
999    5.373404e+06
Name: date, Length: 1000, dtype: float64

In [33]:
(today-time['date'])/np.timedelta64(1,'h')

0       94043.321625
1       90780.488292
2      102443.804958
3       85691.638292
4       95220.971625
           ...
995    109379.321625
996     93084.921625
997    104244.538292
998    107028.588292
999     89556.738292
Name: date, Length: 1000, dtype: float64